In [1]:
import pandas as pd
import numpy as np
from sklearn.datasets import load_diabetes
from sklearn.linear_model import SGDRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score

In [2]:
X,y = load_diabetes(return_X_y=True) 

In [3]:
print(X.shape) 
print(y.shape) 

(442, 10)
(442,)


In [4]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=2) 

In [5]:
print(X_train.shape) 
print(X_test.shape) 
print(y_train.shape) 
print(y_test.shape) 

(353, 10)
(89, 10)
(353,)
(89,)


In [6]:
SGD = SGDRegressor(max_iter=50,learning_rate='constant',eta0=0.01) 

In [7]:
SGD.fit(X_train,y_train) 

D:\Anaconda\lib\site-packages\sklearn\linear_model\_stochastic_gradient.py:1208: ConvergenceWarning: Maximum number of iteration reached before convergence. Consider increasing max_iter to improve the fit.
  warnings.warn("Maximum number of iteration reached before "


SGDRegressor(learning_rate='constant', max_iter=50)

In [8]:
y_pred = SGD.predict(X_test) 

In [9]:
SGD.coef_

array([  61.34604272,  -18.27160609,  241.30771325,  178.36616715,
         41.71439716,   15.38115772, -134.0390024 ,  119.18464248,
        226.0813994 ,  113.3322284 ])

In [10]:
SGD.intercept_

array([155.05778997])

In [11]:
r2_score(y_test,y_pred) 

0.3847044783350182

### Now WE will make our own model for Stochastic Gradient Descent and then compare it with sklearn model.

In [12]:
class meraSGD:
    
    def __init__(self,epoch=50,learning_rate=0.01):
        self.epoch = epoch
        self.learning_rate = learning_rate
        self.coef_ = None
        self.intercept_ = None
    
    def fit(self,X_train,y_train):
        self.intercept_ = 0
        self.coef_ = np.ones(X_train.shape[1]) 
        for i in range(self.epoch):
            for j in range(X_train.shape[0]):
                idk = np.random.randint(0,X_train.shape[0]) 
                y_hat = self.intercept_ + np.dot(X_train[idk],self.coef_) 
                slope = -2* (y_train[idk] - y_hat)
                step_size = self.learning_rate*slope
                self.intercept_ = self.intercept_ - step_size
                
                slope_m = -2* np.dot((y_train[idk]-y_hat),X_train[idk])
                step_size_m = self.learning_rate*slope_m
                self.coef_ = self.coef_ - step_size_m
        return self.intercept_,self.coef_
    
    def predict(self,X_test):
        return np.dot(X_test,self.coef_) + self.intercept_

In [13]:
SGD1 = meraSGD() 

In [14]:
SGD1.fit(X_train,y_train) 

(157.0237629714824,
 array([  48.90969218,  -73.72717468,  354.40157529,  246.27466116,
          20.31578321,  -27.46856009, -169.89648199,  128.36709288,
         323.93701437,  135.41610264]))

In [15]:
y_pred1 = SGD1.predict(X_test) 

In [16]:
r2_score(y_test,y_pred1) 

0.43153257043268467

##### We have Successfully developed our model for stochastic gradient descent 